apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-cd      
spec:
  project: default
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).   
    syncOptions:
      - CreateNamespace=true
  source:
    chart: argo-cd
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.7.11
    helm:
      releaseName: argo
      values: |
        configs: 
          repositories:
            catalyst-helm: 
              name: "Catalyst Community Public Github Helm Repository"
              type: "helm"
              url: "https://raw.githubusercontent.com/catalystcommunity/charts/main"
              # If this was private we need this.
              #username: "${helmRepoPat}"
              #password: "${helmRepoPat}"
            argo:
              name: "ArgoCD Helm Repository"
              type: "helm"
              url: "https://argoproj.github.io/argo-helm"
        controller:
          logLevel: error
          args:
            appResyncPeriod: "30"
          extraArgs:
            - --app-state-cache-expiration=1s
            - --default-cache-expiration=1s
            - --application-namespaces="argo*"
          metrics:
            enabled: true
            serviceMonitor:

              enabled: true
          resources:
            requests:
              cpu: 300m
              memory: 750Mi

        dex:
          # disable dex for now because we don't do authentication to argocd at all
          enabled: false

        redis:
          metrics:
            enabled: true
            image:
              # specify docker registry because the quay default doesn't work
              repository: bitnami/redis-exporter
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 500Mi

        server:
          logLevel: error
          config:

            timeout.reconciliation: 30s
          extraArgs:
            - --app-state-cache-expiration=1s
            - --default-cache-expiration=1s
            - --application-namespaces="argo*"
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:

            requests:
              cpu: 100m
              memory: 500Mi

        repoServer:
          logLevel: error
          extraArgs:
            - --repo-cache-expiration=1s
            - --default-cache-expiration=1s
            - --revision-cache-expiration=1s
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          resources:
            requests:
              cpu: 300m
              memory: 750Mi
        applicationSet:
          # disable the applicationSet controller because we don't use it and it ends
          # up in a crashloop due to cache syncing timeouts
          enabled: false
